# Taken from https://github.com/browniebroke/cookiecutter-pypackage/blob/main/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install package
        run: |
          python -m pip install -q -U pip -e ."[driver]"
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  release:
    runs-on: ubuntu-latest
    environment: release
    if: github.ref == 'refs/heads/main'
    needs:
      - pre-commit
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run semantic release:
      # - Update CHANGELOG.md
      # - Update version in code
      # - Create git tag
      # - Create Github release
      # - Publish to PyPI
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@v7.15.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
